version: "3"

volumes:
  postgres_volume:

services:
  postgres:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: 'polls'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      DOCKER_CERT_PATH: /home/ya/.docker/machine/certs/
    expose:
      - 5432
    ports:
    - 5432:5432

