# Generated by Django 2.2.10 on 2021-01-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_auto_20210127_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpoint',
            old_name='point',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='point',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_answer',
        ),
        migrations.AddField(
            model_name='questionpoint',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls_app.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquestion',
            name='text_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
