# Generated by Django 2.2.10 on 2021-01-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0003_auto_20210127_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='question_point',
            field=models.ManyToManyField(null=True, to='polls_app.QuestionPoint'),
        ),
    ]
